### ISSUE TITLE
TypeError During training

### ISSUE THREAD

**Issue by ezraguo-dev** [QiangAIResearcher/sahp_repo#5]
Hello guys,

I encountered the below error when training the SAHP model with your repo.

Traceback (most recent call last):
  File "D:/Ref/Point Process/sahp_repo-master/main_func.py", line 206, in <module>
    model = train_eval_sahp(params)
  File "D:\Ref\Point Process\sahp_repo-master\train_functions\train_sahp.py", line 148, in train_eval_sahp
    nll = model.compute_loss(batch_seq_times, batch_onehot)
  File "D:\Ref\Point Process\sahp_repo-master\models\sahp.py", line 111, in compute_loss
    intens_at_evs = nn.utils.rnn.pad_sequence(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\utils\rnn.py", line 363, in pad_sequence
    return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
TypeError: pad_sequence(): argument 'sequences' (position 1) must be tuple of Tensors, not Tensor

Could you give me some advice?
Thanks

**Comment by ezraguo-dev** [comment]
This problem may cause by the Torch version. I update the code by,
        intens_at_samples = nn.utils.rnn.pad_sequence(
            [x for x in intens_at_samples], padding_value=0.0, batch_first=True)
The code work now, do you consider this change would influence the mode training?
